inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/*.rb'
    - '**/Gemfile'
    - environments/**/*.rb
    - roles/**/*.rb
    - .chef/**/*.rb
  Exclude:
    - cookbooks/**/*
    - vms/**/*
    - nodes/**/*
